"""Room truth, server side.

Mirrors `webapp/data.js` — edit both together. The bot never trusts the price
or total that arrives in the Mini App payload (a client can tamper with it);
it recomputes both from this file.

`price` is som per night; `None` means the hotel has not set one.

Generated by the hotel-miniapp skill from the photo folders. Re-running the
ingest script rewrites the ROOMS list below.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Room:
    id: str
    plate: str
    price: int | None
    shared: bool = False
    # Shared spaces have no number, so they carry their own name in both
    # languages instead of one hard-coded pair.
    uz_name: str = ""
    ru_name: str = ""

    def label(self, lang: str) -> str:
        if self.shared:
            return self.uz_name if lang == "uz" else self.ru_name
        return f"{self.plate}-xona" if lang == "uz" else f"Номер {self.plate}"


ROOMS: list[Room] = [
    Room("2", "2", 450_000),
    Room("4", "4", 350_000),
    Room("5", "5", 350_000),
    Room("8", "8", 300_000),
    Room("9", "9", 400_000),
    Room("11", "11", 300_000),
    Room("12", "12", 300_000),
    Room("kirishqismi", "KIR", None, shared=True, uz_name="Kirish qismi", ru_name="Входная зона"),
]

BY_ID = {room.id: room for room in ROOMS}
